<main>
			<section class="banner">
				<div id="ei-slider" class="ei-slider">
                    <ul class="ei-slider-large">
                    	<li>
                            <img src="images/images/large/1.jpg" alt="image01" class="noneMobile"/>
                            <img src="images/images/large/1-mobile.jpg" alt="image01" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>mais proteção para você e seus bens</h3>                            <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>
						<li>
                            <img src="images/images/large/6.jpg" alt="image06" class="noneMobile"/>
                            <img src="images/images/large/1-mobile.jpg" alt="image02" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>2</h3>                            
                                <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>  
                        <li>
                            <img src="images/images/large/2.jpg" alt="image02" class="noneMobile" />
                            <img src="images/images/large/1-mobile.jpg" alt="image03" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>3</h3>                            
                                <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>
                        <li>
                            <img src="images/images/large/3.jpg" alt="image03" class="noneMobile"/>
                            <img src="images/images/large/1-mobile.jpg" alt="image04" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>3</h3>                            
                                <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>
                        <li>
                            <img src="images/images/large/4.jpg" alt="image04" class="noneMobile"/>
                            <img src="images/images/large/1-mobile.jpg" alt="image05" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>3</h3>                            
                                <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>
                        <li>
                            <img src="images/images/large/5.jpg" alt="image05" class="noneMobile"/>
                            <img src="images/images/large/1-mobile.jpg" alt="image06" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>3</h3>                            
                                <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>
                        <li>
                            <img src="images/images/large/7.jpg" alt="image07" class="noneMobile"/>
                            <img src="images/images/large/1-mobile.jpg" alt="image07" class="noneDesktop noneTablet"/>
                            <div class="ei-title">
                                <h2></h2>
                                <h3>3</h3>                            
                                <p>Rastreie e localize seu veiculo a qualquer hora! Proteja-se em situações emergenciais com o Botão de Pânico.</p>
                                <a href="#" title="SAIBA MAIS">Saiba mais</a>
                            </div>
                        </li>
                    </ul><!-- ei-slider-large -->
                    <ul class="ei-slider-thumbs">
                        <li class="ei-slider-element">Current</li>
						<li><a href="#">6</a><img src="images/images/thumbs/6.jpg" alt="thumb06" /></li>
                        <li><a href="#">1</a><img src="images/images/thumbs/1.jpg" alt="thumb01" /></li>
                        <li><a href="#">2</a><img src="images/images/thumbs/2.jpg" alt="thumb02" /></li>
                        <li><a href="#">3</a><img src="images/images/thumbs/3.jpg" alt="thumb03" /></li>
                        <li><a href="#">4</a><img src="images/images/thumbs/4.jpg" alt="thumb04" /></li>
                        <li><a href="#">5</a><img src="images/images/thumbs/5.jpg" alt="thumb05" /></li>
                        <li><a href="#">7</a><img src="images/images/thumbs/7.jpg" alt="thumb07" /></li>
                    </ul><!-- ei-slider-thumbs -->
                </div><!-- ei-slider -->


				<!--<img src="images/desktop/img-banner.jpg" class="noneMobile">
				<img src="images/mobile/img-banner.jpg" class="noneTablet noneDesktop">-->
			</section>
			<section class="destaque">
				<a href="#" title="Tele View"></a>
			</section>
			<section class="servicos">
				<div class="container">

							<ul class="servicos-mobile noneDesktop noneTablet">
								<li>
									<a href="#"  title="Alarmes">
										<img src="images/desktop/alarme.jpg">
										<div>
											<h2>Alarmes</h2>
											<p>Projeta sua casa ou comércio com Sistema de Alarme e Monitoramento e tenha controle total do acionamento, inclusive à distância.</p>
										</div>
									</a>
								</li>
								<li>
									<a href="#"  title="Câmeras">
										<img src="images/desktop/cameras.jpg">
										<div>
											<h2>Câmeras</h2>
											<p>Tenha acesso a todos os equipamentos para implementação do seu sistema de monitoramento.</p>
										</div>
									</a>
								</li>
								<li>
									<a href="#"  title="Rastreamento">
										<img src="images/desktop/rastreamento.jpg">
										<div>
											<h2>Rastreamento</h2>
											<p>Localização de veículos com Botão de Pânico: rastreie e localize seu veiculo a qualquer hora!</p>
										</div>
									</a>
								</li>
							</ul>

							<div id="owl-demo" class="owl-carousel owl-theme noneMobile">
								<div class="item-servico">
									<a href="#"  title="Alarmes">
										<figure><img src="images/desktop/alarme.jpg"></figure>
										<h2>Alarme</h2>
										<p>Projeta sua casa ou comércio com Sistema de Alarme e Monitoramento e tenha controle total do acionamento, inclusive à distância.</p>
									</a>
								</div>
								<div class="item-servico">
									<a href="#"  title="Câmeras">
										<figure><img src="images/desktop/cameras.jpg"></figure>
										<h2>Câmeras</h2>
										<p>Tenha acesso a todos os equipamentos para implementação do seu sistema de monitoramento.</p> 
										<p>Conte com a Teleatlantic para obter a melhor solução em segurança patrimonial do mercado.</p>
									</a>
								</div>
								<div class="item-servico">
									<a href="#"  title="Rastreamento">
										<figure><img src="images/desktop/rastreamento.jpg"></figure>
										<h2>Rastreamento</h2>
										<p>Localização de veículos com Botão de Pânico: rastreie e localize seu veiculo a qualquer hora!</p>
									</a>
								</div>
								<div class="item-servico">
									<a href="#"  title="Rastreamento">
										<figure><img src="images/desktop/rastreamento.jpg"></figure>
										<h2>Rastreamento</h2>
										<p>Localização de veículos com Botão de Pânico: rastreie e localize seu veiculo a qualquer hora!</p>
									</a>
								</div>
								<div class="item-servico">
									<a href="#"  title="Rastreamento">
										<figure><img src="images/desktop/rastreamento.jpg"></figure>
										<h2>Rastreamento</h2>
										<p>Localização de veículos com Botão de Pânico: rastreie e localize seu veiculo a qualquer hora!</p>
									</a>
								</div>
							</div>	
				</div>
			</section>
			<section class="como-funciona">
				<div class="container">
					<div class="funciona">
						<h2 class="titulo-interna">Como funciona</h2>	
						<p class="previa">Resposta Imediata.<br/>
						Em poucos segundos, recebemos o alerta, entramos em contato com você e comunicamos às autoridades. Veja abaixo como funciona o serviços de monitoria.</p>
					</div>
					<div id="owl2" class="owl-carousel owl-theme">
						<div class="calculadora">
							<figure class="sprite-icones icone-calculadora"></figure>
							<figcaption>Alerta de Intruso</figcaption>
						</div>
						<div class="wifi">
							<figure class="sprite-icones icone-wifi"></figure>
							<figcaption>É enviado um aviso à Centralde Comando Teleatlantic</figcaption>
						</div>
						<div class="remoto">
							<figure class="sprite-icones icone-remoto"></figure>
							<figcaption>Em caso de alarme, há a possibilidade de ver e ouvir remotamente.</figcaption>
						</div>
						<div class="policia">
							<figure class="sprite-icones icone-carro"></figure>
							<figcaption>É encaminhado um aviso para a polícia.</figcaption>
						</div>
					</div>
				</div>
			</section>
			<section class="other">
				<div class="container">

					<article class="simulador noneMobile">
							<div>
								<h2>Simulador de Proposta</h2>
								<p>Simule seu próprio sistema de segurança informando dados da planta do seu imóvel.
									Avalie os melhores pontos e conheça os equipamentos para instalação do seu alarme.</p>
								<a href="#" title="Saiba mais" class="btn-saiba-mais">Saiba mais</a>
							</div>
							<div>
								<img src="images/img-simulador.png" alt="Simulador de proposta">
							</div>
					</article>

					<article class="representante noneMobile">
							<div>
								<h2>Seja um Representante</h2>
								<p>Aproveite as oportunidades do mercado tornando-se um Representante Autorizado TELEATLANTIC, e descubra como ter sucesso neste segmento que vem crescendo a cada ano no Brasil.</p>
								<a href="#" title="Saiba mais" class="btn-saiba-mais">Saiba mais</a>
							</div>
							<div>
								<img src="images/img-representante.jpg" alt="Seja um representante">
							</div>
					</article>

					<!-- <div id="owl3" class="owl-carousel owl-theme">
						sdadsasdasdasd
					</div> -->
				</div>

				<a href="#" class="simula noneDesktop noneTablet" title="Simulador de Proposta">Simulador de Proposta</a>
				<a href="#" class="simula noneDesktop noneTablet" title="Seja um Representante">Seja um Representante</a>

			</section>
			<section class="contato-consultores">
				<div class="container">
					<div class="infos">

							<h2>Mais informações?</h2>
							<h3>Fale com um de nossos consultores!</h3>
							<p>Preencha os campos ao lado informando seu interesse e solicite um contato de um de nossos consultores. </p>
							<p>Ou entre em contato usando um dos telefones abaixo:</p>
							<div>
								<p>São Paulo</p>
								<span>(11)</span>
								<span>3811.1000</span>
							</div>
							<div>
								<p>Outras Localidades</p>
								<span>(11)</span>
								<span>4002.7222</span>
							</div>

					</div>

					<div class="form-infos">
						<div class="linha">
							<label>Nome:</label> <input type="text" class="input">
						</div>
						<div class="linha">
							<label>Email:</label> <input type="text" class="input">
						</div>						
						<div class="linha">
							<label>Fone:</label> <input type="text" class="input"> <input type="text" class="input menor"> 
						</div>
						<div class="linha">
							<label>Tenho interesse em sistemas para:</label>
							<select class="input">
								<option>Teste</option>
								<option>Teste</option>
								<option>Teste</option>
							</select>
						</div>
						<div class="linha">
							<label>Tenho interesse nos sistemas de:</label>
							<select class="input">
								<option>Teste</option>
								<option>Teste</option>
								<option>Teste</option>
							</select>
						</div>
						<div class="linha">
							<label>Conheci a Teleatlantic através de:</label>
							<select class="input">
								<option>Teste</option>
								<option>Teste</option>
								<option>Teste</option>
							</select>
						</div>
						<input type="submit" value="solicitar contato" class="btn btn-azul">
					</div>
				</div>
			</section>
		</main>