<header>
	<div class="topo">
		<div class="container">
			<a href="<?php echo $this->baseUrl(); ?>" class="left logo"><img src="images/teleatlantic.png" alt="Teleatlantic"></a>
			<ul class="tel-topo noneMobile">
				<li>
					<p>São Paulo</p>
					<span class="menor">(11)</span>
					<span class="maior">3811-1100</span>
				</li>
				<li>
					<p>Outras localidades</p>
					<span class="maior">4002-7222</span>
				</li>
			</ul>
			<ul class="canal right noneMobile">
				<li>
					<a href="" title="Canal do Cliente" class="canal-cliente">
						<i class="sprite-icones icone icone-canal-do-cliente"></i>
						<span>Canal do Cliente</span>
					</a>
				</li>
				<li>
					<a href="" title="Chat" class="canal-chat">
						<i class="sprite-icones icone icone-chat"></i>
						<span>Chat</span>
					</a>
				</li>
			</ul>
		</div>
	</div>
	<nav class="clear noneMobile">
		<div class="container">
			<ul class="menu">
				<li>
					<a href="javascript:void(0)" style="cursor:default;" title="A Teleatlantic" class="drop">A Teleatlantic</a>
					<ul>
						<li><a href="<?php echo $this->baseUrl(); ?>/institucional/sobre-empresa" title="Sobre a Empresa">Sobre a Empresa</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/institucional/abese" title="ABESE">ABESE</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/institucional/imprensa" title="Imprensa">Imprensa</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/institucional/representantes" title="Seja um representante">Seja um representante</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/institucional/trabalhe-conosco" title="Trabalhe Conosco">Trabalhe Conosco</a></li>
					</ul>
				</li>
				<li>
					<a href="#" title="Soluções em Monitoramento" class="drop">Soluções em Monitoramento</a>
					<ul>
						<li><a href="<?php echo $this->baseUrl(); ?>/solucoes/monitoramento-residencial" title="Monitoramento Residencial">Monitoramento Residencial</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/solucoes/monitoramento-comercial" title="Monitoramento Comercial">Monitoramento Comercial</a></li>
					</ul>
				</li>
				<li>
					<a href="<?php echo $this->baseUrl(); ?>/projetos-especiais" title="Projetos Especiais">Projetos Especiais</a>
				</li>	
				<li>
					<a href="<?php echo $this->baseUrl(); ?>/servicos" title="Serviços" class="drop">Serviços</a>
					<ul>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/teleview" title="Tele View">Tele View</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-gps" title="Tele GPS">Tele GPS</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-online" title="Tele Online">Tele Online</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/supervisao-motorizada" title="Supervisão Motorizada">Supervisão Motorizada</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-ronda" title="Tele Ronda">Tele Ronda</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-service" title="Tele Service">Tele Service</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-control" title="Tele Control">Tele Control</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-aviso-arme" title="Tele Aviso-Arme">Tele Aviso-Arme</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/tele-emergencia" title="Tele Emergência">Tele Emergência</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/esta-de-mudanca" title="Está de mudança?">Está de mudança?</a></li>
						<li><a href="<?php echo $this->baseUrl(); ?>/servicos/servico-manutencao" title="Serviço de Manutenção">Serviço de Manutenção</a></li>
					</ul>
				</li>
				<li>
					<a href="<?php echo $this->baseUrl(); ?>/fale-conosco" title="Fale Conosco">Fale Conosco</a>
				</li>	
				<li>
					<a href="<?php echo $this->baseUrl(); ?>/faq" title="FAQ">FAQ</a>
				</li>	
			</ul>
		</div>
	</nav>

	<!-- MENU MOBILE -->

	<nav class="menu-mobile noneDesktop noneTablet">
		<div class="container">
			<ul class="chat-tel">
				<li><a href="javascript:void(0);" title="Chat" class="icone icone-chat"></a></li>
				<li><a href="javascript:void(0);" title="Telefone" class="icone icone-telefone"></a></li>
				<li class="icone-menu2-mobile"><a href="javascript:void(0);" title="Menu" id="abre-menu" class="icone icone-menu2"></a></li>
			</ul>
			<div class="menu">
				<a href="javascript:void(0);" id="btn-menu" class="icone icone-menu"></a>
				<div class="itens">
					<div class="top">
						<span>canal do CLIENTE</span>
						<input type="submit" class="btn btn-branco" value="entrar">
					</div>
					<ul class="itens-menu">
						<li><a href="" title="">a teleatlantic</a></li>
							<ul class="itens-menu-sub">
								<li><a href="" title="Sobre a empresa">Sobre a empresa</a></li>
								<li><a href="" title="ABESE">ABESE</a></li>
								<li><a href="" title="Imprensa">Imprensa</a></li>
								<li><a href="" title="Trabalhe Conosco" class="sem-borda">Trabalhe Conosco</a></li>
							</ul>
						</li>
						<li><a href="" title="">Monitoramento</a></li>
							<ul class="itens-menu-sub">
								<li><a href="" title="Residencial">Residencial</a></li>
								<li><a href="" title="Comercial" class="sem-borda">Comercial</a></li>
							</ul>
						</li>
						<li><a href="#" title="Serviços">Serviços</a></li>
							<ul class="itens-menu-sub">
								<li><a href="" title="Tele View">Tele View</a></li>
								<li><a href="" title="Tele GPS">Tele GPS</a></li>
								<li><a href="" title="Tele Online">Tele Online</a></li>
								<li><a href="" title="Supervisão Motorizada">Supervisão Motorizada</a></li>
								<li><a href="" title="Tele Ronda">Tele Ronda</a></li>
								<li><a href="" title="Tele Service">Tele Service</a></li>
								<li><a href="" title="Tele Control">Tele Control</a></li>
								<li><a href="" title="Tele Aviso-Arme">Tele Aviso-Arme</a></li>
								<li><a href="" title="Tele Emergência">Tele Emergência</a></li>
								<li><a href="" title="Esta de Mundança">Esta de Mundança</a></li>
								<li><a href="" title="Serviço de Manutenção" class="sem-borda">Serviço de Manutenção</a></li>
							</ul>
						</li>
						<li><a href="#" title="Projetos Especiais">Projetos Especiais</a></li></li>
						<li><a href="#" title="Contato">Contato</a></li></li>
					</ul>
				</div>
 			</div>
		</div>
	</nav>

	<!-- END MENU MOBILE -->

</header>