Ext.namespace('App', 'App.Sistema');

App.Sistema.Password = function() {
	var wndPassword = new Ext.Window({
		title: 'Alterar senha',
		iconCls: 'icon-password',
		modal: true,
		constrain: true,
		closeAction: 'hide',
		resizable: false,
		width: 340,
		items: new Ext.form.FormPanel({
			id: 'sistema-formPassword',
			url: '<?php echo $this->BaseUrl(); ?>/index/change-password',
			method: 'POST',
			monitorValid: true,
			border: false,
			labelWidth: 130,
			bodyStyle: 'padding: 10px;',
			reader: new Ext.data.JsonReader({
				root: 'senha',
				successProperty: 'success'
			}, ['usr_senha', 'usr_senha_nova', 'usr_senha_confirma']),
			errorReader: new Ext.data.JsonReader({
				root: 'errors',
				successProperty: 'success'
			}, ['id', 'msg']),
			listeners: {
				actioncomplete: function(form, action) {
					if ('submit' == action.type) {
						Ext.Msg.show({
							title: wndPassword.title,
							icon: Ext.Msg.INFO,
							msg: form.errorReader.jsonData.message,
							buttons: Ext.Msg.OK,
							fn: function(button, event) {
								wndPassword.hide();
							},
							scope: this
						});
					}
				},
				actionfailed: function(form, action) {
					if ('submit' == action.type) {
						Ext.Msg.show({
							title: wndPassword.title,
							icon: Ext.Msg.ERROR,
							msg: form.errorReader.jsonData.message,
							buttons: Ext.Msg.OK
						});
					}
				},
				scope: this
			},
			defaults: {
				xtype: 'textfield',
				inputType: 'password',
				minLength: 5,
				maxLength: 15,
				allowBlank: false,
				anchor: '100%'
			},
			items: [{
				name: 'usr_senha',
				fieldLabel: 'Senha atual'
			}, {
				name: 'usr_senha_nova',
				fieldLabel: 'Nova senha'
			}, {
				name: 'usr_senha_confirma',
				fieldLabel: 'Confirme a nova senha'
			}],
			buttons: [{
				text: 'Alterar',
				iconCls: 'icon-save-small',
				formBind: true,
				listeners: {
					click: function(button, event) {
						var form = wndPassword.items.get('sistema-formPassword').getForm();
						if (form.isValid()) {
							form.submit({
								waitTitle: wndPassword.title,
								waitMsg: 'Alterando senha...'
							});
						}
					},
					scope: this
				}
			}, {
				text: 'Cancelar',
				iconCls: 'icon-save-cancel-small',
				listeners: {
					click: function(button, event) {
						wndPassword.hide();
					},
					scope: this
				}
			}]
		}),
		listeners: {
			beforeshow: function(wnd) {
				wnd.center();
				wnd.items.get('sistema-formPassword').getForm().reset();
			},
			scope: this
		}
	});

	return {
		init: Ext.emptyFn,

		show: function(sender) {
			wndPassword.show(sender);
		}
	};
}();